### ISSUE TITLE
Error message 

### ISSUE THREAD

**Issue by NooL** [stefanwalther/qvD3BulletCharts#1]
Hi,

I'm using QlikView PE version SR3.
After instaaling the file D3BulletCharts_v1.0.1.qar and inserting the object,
an error message appear. Un fortunately not possible to attach.
 it says  "d3 is undefined"...:
http://qlikview/QvAjaxZfc/QvsViewClient.aspx?public=only&name=Extensions/D3BulletCharts/script.js&xrfkey=ANuQJBkbkJVmImpV
BTW, now it's not possible to use previous extensions anymore.

Thanks,

Dafna

**Comment by stefanwalther** [comment]
Hi Dafna,

which version are you using QlikView 11 SR3 or QlikView 11.2 SR3? Furthermore, which operating system do you have and which Internet Explorer do you have installed?

Unfortunately I cannot reproduce this issue so far, but happy to assist.

Regards
Stefan

**Comment by NooL** [comment]
Hi Stephan,

I'm using version 11.2 of Qlikview.

I have IE version 8.

The OS is Windows XP

You mentioned a path for installing the files. I didn't have the exact same
path.

Therefore, I have created it:

c:\Documents and Settings\Dafna\AppData\Local\Qliktech\QlikView\Extensions\

But it didn't help.  

Hope you'll find a solution :-)

Thanks & Regards,

Dafna

**Comment by stefanwalther** [comment]
Do you now have a folder called "Objects" below the path you've mentioned above?

Regards
Stefan

**Comment by NooL** [comment]
Hi Stephan,

Here is the full path:

c:\Documents and
Settings\Dafna\AppData\Local\Qliktech\QlikView\Extensions\Object\

In this folder I kept your 2 QAR files.

BTW, is there a place to define internet browser in QlikView?

I didn't find anything about it.

I apologize for being a little helpless as far as the extensions go :-)

Thanks & Regards,

Dafna

**Comment by stefanwalther** [comment]
It should be "...\Objects" instad of "..\Object" ... but you do not need to create it manually, just double-click on the .qar file and QlikView will do the rest (as mentioned in the following post http://www.qlikblog.at/1597/qliktip-40-installingdeploying-qlikview-extensions/)

Other question: QlikView always uses IE as the internal browser in WebView ... 

Regards
Stefan

**Comment by NooL** [comment]
Oops.

But clicking the file does not create a folder. Unless it's hidden.

I get this message, but trying to use the extensions still generates the
error messages.

Thanks,

Dafna

**Comment by stefanwalther** [comment]
... if you klick on the .qar file, does QlikView Desktop open?

Regards
Stefan

**Comment by NooL** [comment]
Hi Stephan,

I assume you mean the start page?

Yes, it does if I'm not in a document already.

Thanks,

Dafna

**Comment by stefanwalther** [comment]
Hmm, I am really sorry, have tested it know on several (virtual) machines covering some browser-OS scenarios and the extension worked fine in all scenarios ...

**Comment by NooL** [comment]
Hi Stefan,

That's a pity.

I was inspired by Stephan Few's book, and was challenged re-design some
applications

and use the bullet chart..

I just want to make sure before trying to install it on other machine:

If the path you mentioned doesn't exist, the QAR can be activated from any
other folder?

Thanks for your kind help here :-)

Dafna
